In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('data.csv')
#fetch first five rows
df.head(5)

,year,industry_code_ANZSIC,industry_name_ANZSIC,rme_size_grp,variable,value,unit,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,2011,A,"Agriculture, Forestry and Fishing",a_0,Activity unit,46134,COUNT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2011,A,"Agriculture, Forestry and Fishing",a_0,Rolling mean employees,0,COUNT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2011,A,"Agriculture, Forestry and Fishing",a_0,Salaries and wages paid,279,DOLLARS(millions),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2011,A,"Agriculture, Forestry and Fishing",a_0,"Sales, government funding, grants and subsidies",8187,DOLLARS(millions),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2011,A,"Agriculture, Forestry and Fishing",a_0,Total income,8866,DOLLARS(millions),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
#last 5 rows
df.tail(5)

,year,industry_code_ANZSIC,industry_name_ANZSIC,rme_size_grp,variable,value,unit,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
23215,2025,all,All Industries,j_Grand_Total,Salaries and wages paid,160833,DOLLARS(millions),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23216,2025,all,All Industries,j_Grand_Total,"Sales, government funding, grants and subsidies",854561,DOLLARS(millions),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23217,2025,all,All Industries,j_Grand_Total,Total assets,3068548,DOLLARS(millions),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23218,2025,all,All Industries,j_Grand_Total,Total expenditure,867750,DOLLARS(millions),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23219,2025,all,All Industries,j_Grand_Total,Total income,976077,DOLLARS(millions),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.describe()

               year  Unnamed: 7  Unnamed: 8   Unnamed: 9
count  23220.000000         0.0         0.0    41.000000
mean    2018.000000         NaN         NaN  2022.268293
std        4.320587         NaN         NaN     0.448575
min     2011.000000         NaN         NaN  2022.000000
25%     2014.000000         NaN         NaN  2022.000000
50%     2018.000000         NaN         NaN  2022.000000
75%     2022.000000         NaN         NaN  2023.000000
max     2025.000000         NaN         NaN  2023.000000

In [5]:
df.dtypes

year                      int64
industry_code_ANZSIC        str
industry_name_ANZSIC        str
rme_size_grp                str
variable                    str
value                       str
unit                        str
Unnamed: 7              float64
Unnamed: 8              float64
Unnamed: 9              float64
Unnamed: 10                 str
Unnamed: 11                 str
Unnamed: 12                 str
Unnamed: 13                 str
Unnamed: 14                 str
Unnamed: 15                 str
dtype: object

In [6]:
#handling missing values
df.isnull()

,year,industry_code_ANZSIC,industry_name_ANZSIC,rme_size_grp,variable,value,unit,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True
1,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True
2,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True
3,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True
4,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23215,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True
23216,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True
23217,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True
23218,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True
23219,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True

In [7]:
df[df.isnull()]

,year,industry_code_ANZSIC,industry_name_ANZSIC,rme_size_grp,variable,value,unit,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23215,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23216,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23217,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23218,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23219,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df.isnull().any(axis=1)

0        True
1        True
2        True
3        True
4        True
         ...
23215    True
23216    True
23217    True
23218    True
23219    True
Length: 23220, dtype: bool

In [9]:
df.isnull().any()

year                    False
industry_code_ANZSIC    False
industry_name_ANZSIC    False
rme_size_grp            False
variable                False
value                   False
unit                    False
Unnamed: 7               True
Unnamed: 8               True
Unnamed: 9               True
Unnamed: 10              True
Unnamed: 11              True
Unnamed: 12              True
Unnamed: 13              True
Unnamed: 14              True
Unnamed: 15              True
dtype: bool

In [10]:
df.isnull().sum()

year                        0
industry_code_ANZSIC        0
industry_name_ANZSIC        0
rme_size_grp                0
variable                    0
value                       0
unit                        0
Unnamed: 7              23220
Unnamed: 8              23220
Unnamed: 9              23179
Unnamed: 10             23177
Unnamed: 11             23179
Unnamed: 12             23179
Unnamed: 13             23179
Unnamed: 14             23179
Unnamed: 15             23179
dtype: int64

In [12]:
df_filled=df.fillna(0)

In [13]:
df_filled

,year,industry_code_ANZSIC,industry_name_ANZSIC,rme_size_grp,variable,value,unit,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,2011,A,"Agriculture, Forestry and Fishing",a_0,Activity unit,46134,COUNT,0.0,0.0,0.0,0,0,0,0,0,0
1,2011,A,"Agriculture, Forestry and Fishing",a_0,Rolling mean employees,0,COUNT,0.0,0.0,0.0,0,0,0,0,0,0
2,2011,A,"Agriculture, Forestry and Fishing",a_0,Salaries and wages paid,279,DOLLARS(millions),0.0,0.0,0.0,0,0,0,0,0,0
3,2011,A,"Agriculture, Forestry and Fishing",a_0,"Sales, government funding, grants and subsidies",8187,DOLLARS(millions),0.0,0.0,0.0,0,0,0,0,0,0
4,2011,A,"Agriculture, Forestry and Fishing",a_0,Total income,8866,DOLLARS(millions),0.0,0.0,0.0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23215,2025,all,All Industries,j_Grand_Total,Salaries and wages paid,160833,DOLLARS(millions),0.0,0.0,0.0,0,0,0,0,0,0
23216,2025,all,All Industries,j_Grand_Total,"Sales, government funding, grants and subsidies",854561,DOLLARS(millions),0.0,0.0,0.0,0,0,0,0,0,0
23217,2025,all,All Industries,j_Grand_Total,Total assets,3068548,DOLLARS(millions),0.0,0.0,0.0,0,0,0,0,0,0
23218,2025,all,All Industries,j_Grand_Total,Total expenditure,867750,DOLLARS(millions),0.0,0.0,0.0,0,0,0,0,0,0
23219,2025,all,All Industries,j_Grand_Total,Total income,976077,DOLLARS(millions),0.0,0.0,0.0,0,0,0,0,0,0

In [ ]:
#filling missing val of year with mean of the col
df['Year_fillNA']=df['year'].fillna(df['year'].mean())
df

,year,industry_code_ANZSIC,industry_name_ANZSIC,rme_size_grp,variable,value,unit,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Value_fillNA,Year_fillNA
0,2011,A,"Agriculture, Forestry and Fishing",a_0,Activity unit,46134,COUNT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011,2011
1,2011,A,"Agriculture, Forestry and Fishing",a_0,Rolling mean employees,0,COUNT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011,2011
2,2011,A,"Agriculture, Forestry and Fishing",a_0,Salaries and wages paid,279,DOLLARS(millions),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011,2011
3,2011,A,"Agriculture, Forestry and Fishing",a_0,"Sales, government funding, grants and subsidies",8187,DOLLARS(millions),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011,2011
4,2011,A,"Agriculture, Forestry and Fishing",a_0,Total income,8866,DOLLARS(millions),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011,2011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23215,2025,all,All Industries,j_Grand_Total,Salaries and wages paid,160833,DOLLARS(millions),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025,2025
23216,2025,all,All Industries,j_Grand_Total,"Sales, government funding, grants and subsidies",854561,DOLLARS(millions),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025,2025
23217,2025,all,All Industries,j_Grand_Total,Total assets,3068548,DOLLARS(millions),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025,2025
23218,2025,all,All Industries,j_Grand_Total,Total expenditure,867750,DOLLARS(millions),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025,2025
23219,2025,all,All Industries,j_Grand_Total,Total income,976077,DOLLARS(millions),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025,2025

In [19]:
df.dtypes

year                      int64
industry_code_ANZSIC        str
industry_name_ANZSIC        str
rme_size_grp                str
variable                    str
value                       str
unit                        str
Unnamed: 7              float64
Unnamed: 8              float64
Unnamed: 9              float64
Unnamed: 10                 str
Unnamed: 11                 str
Unnamed: 12                 str
Unnamed: 13                 str
Unnamed: 14                 str
Unnamed: 15                 str
Value_fillNA              int64
Year_fillNA               int64
dtype: object

In [20]:
#renaming the col
df=df.rename(columns={'value':'Sales Value'})
df.head()

,year,industry_code_ANZSIC,industry_name_ANZSIC,rme_size_grp,variable,Sales Value,unit,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Value_fillNA,Year_fillNA
0,2011,A,"Agriculture, Forestry and Fishing",a_0,Activity unit,46134,COUNT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011,2011
1,2011,A,"Agriculture, Forestry and Fishing",a_0,Rolling mean employees,0,COUNT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011,2011
2,2011,A,"Agriculture, Forestry and Fishing",a_0,Salaries and wages paid,279,DOLLARS(millions),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011,2011
3,2011,A,"Agriculture, Forestry and Fishing",a_0,"Sales, government funding, grants and subsidies",8187,DOLLARS(millions),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011,2011
4,2011,A,"Agriculture, Forestry and Fishing",a_0,Total income,8866,DOLLARS(millions),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011,2011

In [21]:
df=df.rename(columns={'year':'Sales Year'})
df.head()

,Sales Year,industry_code_ANZSIC,industry_name_ANZSIC,rme_size_grp,variable,Sales Value,unit,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Value_fillNA,Year_fillNA
0,2011,A,"Agriculture, Forestry and Fishing",a_0,Activity unit,46134,COUNT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011,2011
1,2011,A,"Agriculture, Forestry and Fishing",a_0,Rolling mean employees,0,COUNT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011,2011
2,2011,A,"Agriculture, Forestry and Fishing",a_0,Salaries and wages paid,279,DOLLARS(millions),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011,2011
3,2011,A,"Agriculture, Forestry and Fishing",a_0,"Sales, government funding, grants and subsidies",8187,DOLLARS(millions),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011,2011
4,2011,A,"Agriculture, Forestry and Fishing",a_0,Total income,8866,DOLLARS(millions),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011,2011

In [ ]:
#changing the datatype
df['Sales_year_new']=df['Sales Year'].astype(float)
df.head()

,Sales Year,industry_code_ANZSIC,industry_name_ANZSIC,rme_size_grp,variable,Sales Value,unit,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Value_fillNA,Year_fillNA,Sales_year_new
0,2011,A,"Agriculture, Forestry and Fishing",a_0,Activity unit,46134,COUNT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011,2011,2011.0
1,2011,A,"Agriculture, Forestry and Fishing",a_0,Rolling mean employees,0,COUNT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011,2011,2011.0
2,2011,A,"Agriculture, Forestry and Fishing",a_0,Salaries and wages paid,279,DOLLARS(millions),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011,2011,2011.0
3,2011,A,"Agriculture, Forestry and Fishing",a_0,"Sales, government funding, grants and subsidies",8187,DOLLARS(millions),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011,2011,2011.0
4,2011,A,"Agriculture, Forestry and Fishing",a_0,Total income,8866,DOLLARS(millions),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011,2011,2011.0

In [25]:
df['New Year']=df['Sales Year'].apply(lambda x:x*2)
df.head()

,Sales Year,industry_code_ANZSIC,industry_name_ANZSIC,rme_size_grp,variable,Sales Value,unit,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Value_fillNA,Year_fillNA,Sales_year_new,New Year
0,2011,A,"Agriculture, Forestry and Fishing",a_0,Activity unit,46134,COUNT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011,2011,2011.0,4022
1,2011,A,"Agriculture, Forestry and Fishing",a_0,Rolling mean employees,0,COUNT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011,2011,2011.0,4022
2,2011,A,"Agriculture, Forestry and Fishing",a_0,Salaries and wages paid,279,DOLLARS(millions),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011,2011,2011.0,4022
3,2011,A,"Agriculture, Forestry and Fishing",a_0,"Sales, government funding, grants and subsidies",8187,DOLLARS(millions),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011,2011,2011.0,4022
4,2011,A,"Agriculture, Forestry and Fishing",a_0,Total income,8866,DOLLARS(millions),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011,2011,2011.0,4022

In [26]:
#data aggregating and grouping
df.head()

,Sales Year,industry_code_ANZSIC,industry_name_ANZSIC,rme_size_grp,variable,Sales Value,unit,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Value_fillNA,Year_fillNA,Sales_year_new,New Year
0,2011,A,"Agriculture, Forestry and Fishing",a_0,Activity unit,46134,COUNT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011,2011,2011.0,4022
1,2011,A,"Agriculture, Forestry and Fishing",a_0,Rolling mean employees,0,COUNT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011,2011,2011.0,4022
2,2011,A,"Agriculture, Forestry and Fishing",a_0,Salaries and wages paid,279,DOLLARS(millions),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011,2011,2011.0,4022
3,2011,A,"Agriculture, Forestry and Fishing",a_0,"Sales, government funding, grants and subsidies",8187,DOLLARS(millions),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011,2011,2011.0,4022
4,2011,A,"Agriculture, Forestry and Fishing",a_0,Total income,8866,DOLLARS(millions),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011,2011,2011.0,4022

In [29]:
grouped_mean=df.groupby('variable')['Sales Year'].mean()
print(grouped_mean)

variable
Activity unit                                      2018.0
Fixed tangible assets                              2018.0
Operating profit before tax                        2018.0
Rolling mean employees                             2018.0
Salaries and wages paid                            2018.0
Sales, government funding, grants and subsidies    2018.0
Total assets                                       2018.0
Total expenditure                                  2018.0
Total income                                       2018.0
Name: Sales Year, dtype: float64

In [30]:
grouped_sum=df.groupby(['variable', 'rme_size_grp'])['Sales Year'].sum()
print(grouped_sum)

variable       rme_size_grp
Activity unit  a_0                 575130
               b_1-5               575130
               c_6-9               575130
               d_10-19             575130
               e_20-49             575130
                                    ...
Total income   f_50-99             575130
               g_100-199           575130
               h_200+              575130
               i_Industry_Total    575130
               j_Grand_Total        30270
Name: Sales Year, Length: 90, dtype: int64

In [32]:
grouped_agg=df.groupby('variable')['Sales Year'].agg(['mean', 'sum', 'count'])
print(grouped_agg)

                                                   mean      sum  count
variable
Activity unit                                    2018.0  5206440   2580
Fixed tangible assets                            2018.0  5206440   2580
Operating profit before tax                      2018.0  5206440   2580
Rolling mean employees                           2018.0  5206440   2580
Salaries and wages paid                          2018.0  5206440   2580
Sales, government funding, grants and subsidies  2018.0  5206440   2580
Total assets                                     2018.0  5206440   2580
Total expenditure                                2018.0  5206440   2580
Total income                                     2018.0  5206440   2580

In [46]:
#merging and joining dataframes
#create sample dataframes
df1=pd.DataFrame({'Key': ['A','B','C'], 'Value1': [1,2,3]})
df2=pd.DataFrame({'Key': ['D','B','C'], 'Value1': [0,2,9]})

In [47]:
df1

  Key  Value1
0   A       1
1   B       2
2   C       3

In [48]:
df2

  Key  Value1
0   D       0
1   B       2
2   C       9

In [49]:
#merge dataframe on the 'key columns'
pd.merge(df1,df2,on="Key",how="inner")

  Key  Value1_x  Value1_y
0   B         2         2
1   C         3         9

In [ ]:
#here all the keys are considered in outer joint whereas in inner joint only common keys are considered
pd.merge(df1,df2,on="Key",how="outer")

  Key  Value1_x  Value1_y
0   A       1.0       NaN
1   B       2.0       2.0
2   C       3.0       9.0
3   D       NaN       0.0

In [ ]:
#left dataframe here df1 will be prioritised more
pd.merge(df1,df2,on="Key",how="left")

  Key  Value1_x  Value1_y
0   A         1       NaN
1   B         2       2.0
2   C         3       9.0

In [52]:
pd.merge(df1,df2,on="Key",how="right")

  Key  Value1_x  Value1_y
0   D       NaN         0
1   B       2.0         2
2   C       3.0         9