In [ ]:
!pip install pandas

Requirement already satisfied: pandas in C:\Users\Asus\OneDrive\Desktop\PYTHON\venv\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\Asus\OneDrive\Desktop\PYTHON\venv\Lib\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Asus\OneDrive\Desktop\PYTHON\venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Asus\OneDrive\Desktop\PYTHON\venv\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\Asus\OneDrive\Desktop\PYTHON\venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd

In [ ]:
#series- A pandas series is 1-D array like object that can hold any data type
import pandas as pd
data=[1,2,3,4,5,9]
series=pd.Series(data)
print(series)
print(type(series))

0    1
1    2
2    3
3    4
4    5
5    9
dtype: int64
<class 'pandas.Series'>

In [ ]:
#create series from dictionary elements
#here key of dictionary become indexes
data={'a':1, 'b':2, 'c': 3, 'd':4}
series_dict=pd.Series(data)
print(series_dict)

a    1
b    2
c    3
d    4
dtype: int64

In [ ]:
data =[3,5,7,9]
indexes=['b','h','a','o']
pd.Series(data, index=indexes)

b    3
h    5
a    7
o    9
dtype: int64

In [ ]:
#Dataframe
#create a dataframe from dict of list
data={
    'Name': ['hiba', 'naba', 'alham'],
    'age': [21,20,16],
    'city': ['bgp', 'lmp', 'lko']
}
df=pd.DataFrame(data)
print(df)
print(type(df))

    Name  age city
0   hiba   21  bgp
1   naba   20  lmp
2  alham   16  lko
<class 'pandas.DataFrame'>

In [ ]:
import numpy as np
np.array(data)

array({'Name': ['hiba', 'naba', 'alham'], 'age': [21, 20, 16], 'city': ['bgp', 'lmp', 'lko']},
      dtype=object)

In [ ]:
#create a dataframe from list of dict
data=[
    {'name': 'hiba', 'age': 20, 'city': 'bgp'},
    {'name': 'naba', 'age': 21, 'city': 'lko'},
    {'name': 'alham', 'age': 17, 'city': 'blr'}

]
df=pd.DataFrame(data)
print(df)
print(type(df))

    name  age city
0   hiba   20  bgp
1   naba   21  lko
2  alham   17  blr
<class 'pandas.DataFrame'>

In [ ]:
df

    name  age city
0   hiba   20  bgp
1   naba   21  lko
2  alham   17  blr

In [ ]:
df['name']

0     hiba
1     naba
2    alham
Name: name, dtype: str

In [ ]:
type(df['name'])

pandas.Series

In [ ]:
df.loc[0]

name    hiba
age       20
city     bgp
Name: 0, dtype: object

In [ ]:
df.iloc[0]

name    hiba
age       20
city     bgp
Name: 0, dtype: object

In [ ]:
df.iloc[0]['name']

'hiba'

In [ ]:
df.iloc[1]['name']

'naba'

In [ ]:
df.iloc[2]['city']

'blr'

In [ ]:
df[0]['name']

KeyError: 0

In [ ]:
df.iloc[0][0]

KeyError: 0

In [ ]:
#accesing elements using at
df.at[1,'age']

np.int64(21)

In [ ]:
print(df.at[1,'age'])

21

In [ ]:
print(df.at[2,'name'])

alham

In [ ]:
#accesing elements using iat
print(df.iat[1,1])

21

In [ ]:
#data manipulation with dataFrame
df

    name  age city
0   hiba   20  bgp
1   naba   21  lko
2  alham   17  blr

In [ ]:
#adding a new col
df['Salary']=[50000,80000,90000]
df

    name  age city  Salary
0   hiba   20  bgp   50000
1   naba   21  lko   80000
2  alham   17  blr   90000

In [ ]:
df.drop('Salary')

KeyError: "['Salary'] not found in axis"

In [ ]:
df

    name  age city  Salary
0   hiba   20  bgp   50000
1   naba   21  lko   80000
2  alham   17  blr   90000

In [ ]:
df.drop('Salary', axis=1)
#this deleted the salary col but not permsnently

    name  age city
0   hiba   20  bgp
1   naba   21  lko
2  alham   17  blr

In [ ]:
df

    name  age city  Salary
0   hiba   20  bgp   50000
1   naba   21  lko   80000
2  alham   17  blr   90000

In [ ]:
df.drop('Salary', axis=1, inplace=True)
#this permanently deleted the salary col

In [ ]:
df

    name  age city
0   hiba   20  bgp
1   naba   21  lko
2  alham   17  blr

In [ ]:
df['age']=df['age']+1
df

    name  age city
0   hiba   21  bgp
1   naba   22  lko
2  alham   18  blr

In [ ]:
df.drop(0,inplace=True)

In [ ]:
df

    name  age city
1   naba   22  lko
2  alham   18  blr